export const encryptedFormAbi = [
  {
    type: "function",
    name: "settings",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "kind", type: "uint8" },
      { name: "showLiveResults", type: "bool" },
      { name: "rewardEnabled", type: "bool" },
      { name: "rewardPerSubmission", type: "uint256" },
      { name: "maxRewardRecipients", type: "uint256" },
      { name: "schemaHash", type: "bytes32" },
      { name: "fheQuestionCount", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "creator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "totalSubmissions",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "rewardsPaidCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "hasSubmitted",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "fheAnswersRecorded",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "fheAnswerProgress",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "slotCounts",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "questionKinds",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "respondentCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getRespondent",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "submitFheQuestion",
    stateMutability: "nonpayable",
    inputs: [
      { name: "questionIndex", type: "uint8" },
      {
        name: "values",
        type: "tuple[]",
        components: [
          { name: "ctHash", type: "uint256" },
          { name: "securityZone", type: "uint8" },
          { name: "utype", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitFheAnswer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "questionIndex", type: "uint8" },
      {
        name: "encryptedChoice",
        type: "tuple",
        components: [
          { name: "ctHash", type: "uint256" },
          { name: "securityZone", type: "uint8" },
          { name: "utype", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitFheAnswers",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "encryptedChoices",
        type: "tuple[]",
        components: [
          { name: "ctHash", type: "uint256" },
          { name: "securityZone", type: "uint8" },
          { name: "utype", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeSubmission",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "getEncryptedTally",
    stateMutability: "view",
    inputs: [
      { name: "questionIndex", type: "uint8" },
      { name: "optionIndex", type: "uint8" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getEncryptedTextChunk",
    stateMutability: "view",
    inputs: [
      { name: "respondent", type: "address" },
      { name: "questionIndex", type: "uint8" },
      { name: "chunkIndex", type: "uint8" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allowCreatorToViewTallies",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "getPublishedTally",
    stateMutability: "view",
    inputs: [
      { name: "questionIndex", type: "uint8" },
      { name: "optionIndex", type: "uint8" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "publishTallyResult",
    stateMutability: "nonpayable",
    inputs: [
      { name: "questionIndex", type: "uint8" },
      { name: "optionIndex", type: "uint8" },
      { name: "plaintext", type: "uint32" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getBountyBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const formFactoryAbi = [
  {
    type: "function",
    name: "createForm",
    stateMutability: "payable",
    inputs: [
      {
        name: "settings",
        type: "tuple",
        components: [
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "kind", type: "uint8" },
          { name: "showLiveResults", type: "bool" },
          { name: "rewardEnabled", type: "bool" },
          { name: "rewardPerSubmission", type: "uint256" },
          { name: "maxRewardRecipients", type: "uint256" },
          { name: "schemaHash", type: "bytes32" },
          { name: "fheQuestionCount", type: "uint8" },
        ],
      },
      { name: "slotCountsPerQuestion", type: "uint8[]" },
      { name: "questionKinds", type: "uint8[]" },
    ],
    outputs: [{ name: "formAddress", type: "address" }],
  },
  {
    type: "function",
    name: "getCreatorForms",
    stateMutability: "view",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    type: "event",
    name: "FormCreated",
    inputs: [
      { name: "form", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "schemaHash", type: "bytes32", indexed: false },
      { name: "kind", type: "uint8", indexed: false },
      { name: "showLiveResults", type: "bool", indexed: false },
      { name: "rewardEnabled", type: "bool", indexed: false },
      { name: "rewardPerSubmission", type: "uint256", indexed: false },
      { name: "maxRewardRecipients", type: "uint256", indexed: false },
      { name: "fheQuestionCount", type: "uint8", indexed: false },
    ],
  },
] as const;
